### ISSUE TITLE
January release

### ISSUE THREAD

**Issue by simonhilpert** [oemof/oemof_base#63]
29th of january the next release oemof v 0.0.3 will be there, the focus should be on test. 

Reminder: 
@oemof/oemof-main  

* Add informations to whats new file v.0.0.3 on dev 
* Merge everything (tested) that should be included until friday

@caro-rli  : can you add the demand-lib information to the whats-newfile on dev?

**Comment by uvchik** [comment]
@caro-rli will not work this week. May you do it?

**Comment by uvchik** [comment]
I think we can give ourself a pat on the back. Since our last release github logged the following changes:

Excluding merges, **7 authors** have pushed **167 commits** to dev and **211** commits to all branches. On dev, **39 files** have changed and there have been **4,435 additions** and **555 deletions**. 

Sounds like a living project :smile:

**Comment by ckaldemeyer** [comment]
:-)
